services:

  database:
    image: postgres:15.7-alpine
    ports:
      - "5435:5432"
    # command: -c 'log_statement=all'  # uncomment to debug
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      PGPORT: "5432"
    # We want persistence for our database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 14s
      retries: 15
      start_period: 2m

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery-worker:
    build:
      context: sandbox_worker
      dockerfile: Dockerfile
    volumes:
      - ./sandbox_worker:/app
      - ../../sample_data:/data
    depends_on:
      - redis
    environment:
      REDIS_CONNECTION_STRING: redis://redis:6379
      DB_URI: postgres://postgres:postgres@database:5432/postgres?sslmode=disable
    command: celery -A tasks worker -B --loglevel=info

  ranker:
    build:
      context: ranking_server
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      REDIS_CONNECTION_STRING: redis://redis:6379
      SCORER_QUEUE_BROKER: redis://redis-scorer-queue:6380
      SCORER_QUEUE_BACKEND: redis://redis-scorer-queue:6380
    command: uvicorn ranking_server.ranking_server:app --host 0.0.0.0 --port 8001 --log-config ranking_server/logging_config.yaml
    ports:
      - "8001:8001"

  redis-scorer-queue:
    image: redis
    ports:
      - "6380:6380"
    command: ["redis-server", "--port", "6380"]

  celery-scorer-worker0:
    build:
      context: scorer_worker
      dockerfile: Dockerfile.scorer_worker
    depends_on:
      - redis-scorer-queue
    environment:
      SCORER_QUEUE_BROKER: redis://redis-scorer-queue:6380
      SCORER_QUEUE_BACKEND: redis://redis-scorer-queue:6380
    command: celery -A scorer_worker.celery_app worker --loglevel=info

  celery-scorer-worker1:
    build:
      context: scorer_worker
      dockerfile: Dockerfile.scorer_worker
    depends_on:
      - redis-scorer-queue
    environment:
      SCORER_QUEUE_BROKER: redis://redis-scorer-queue:6380
      SCORER_QUEUE_BACKEND: redis://redis-scorer-queue:6380
    command: celery -A scorer_worker.celery_app worker --loglevel=info

volumes:
  postgres_data:
    driver: local
